import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        paper: "var(--paper)",
        "paper-2": "var(--paper-2)",
        "paper-muted": "var(--paper-muted)",
        ink: "var(--ink)",
        "ink-body": "var(--ink-body)",
        "ink-soft": "var(--ink-soft)",
        vermilion: "var(--vermilion)",
        marigold: "var(--marigold)",
        "ledger-green": "var(--ledger-green)",
        rule: "var(--rule)",
        "rule-strong": "var(--rule-strong)",
        pin: {
          red: "#e60023",
          pressed: "#cc001f",
          light: "#fef0f2",
        },
        charcoal: "#262622",
        blue: {
          50: "#f0f6ff",
          100: "#e0edff",
          200: "#c2dcff",
          300: "#94c2ff",
          400: "#5ca1ff",
          500: "#435ee5",
          600: "#435ee5",
          700: "#344cc4",
          800: "#273ba3",
          900: "#1d2c80",
        },
        slate: {
          50: "#fbfbf9",
          100: "#f6f6f3",
          200: "#e5e5e0",
          300: "#dadad3",
          400: "#9e9e96",
          500: "#62625b",
          600: "#45453f",
          700: "#33332e",
          800: "#262622",
          900: "#111110",
        },
        fintech: {
          blue: "#435ee5",
          "blue-light": "#f0f6ff",
          "blue-dark": "#344cc4",
          navy: "#111110",
          slate: "#62625b",
          border: "#e5e5e0",
          card: "#ffffff",
          bg: "#fbfbf9",
        },
        apple: {
          blue: "#435ee5",
          focus: "#435ee5",
          canvas: "#ffffff",
          subtle: "#fbfbf9",
          text: "#111110",
          secondary: "#62625b",
          divider: "#e5e5e0",
          dark: "#1c1c1a",
          green: "#16a34a",
          red: "#9e0a0a",
          orange: "#ff9500",
        },
      },
      borderRadius: {
        lg: "1rem",
        xl: "1rem",
        "2xl": "1rem",
        "3xl": "2rem",
        panel: "2rem",
      },
      fontFamily: {
        serif: ["system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        sans: ["system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["ui-monospace", "'SF Mono'", "'JetBrains Mono'", "monospace"],
        hand: ["Caveat", "cursive"],
      },
      boxShadow: {
        none: "none",
        sm: "none",
        DEFAULT: "none",
        md: "none",
        lg: "none",
        card: "none",
        "card-hover": "none",
        modal: "0 20px 40px -15px rgba(17, 17, 16, 0.15)",
        "2xl": "0 20px 40px -15px rgba(17, 17, 16, 0.15)",
      },
    },
  },
  plugins: [],
};
export default config;
